name: "MiSTer build db"
description: "Builds db file for distribution"
inputs:
  db-name:
    description: "Name of DB (value used by downloader)"
    required: false
  dryrun:
    description: "Flag to skip commiting"
    required: false
runs:
  using: "composite"
  steps:
    - name: Install apt-get utilities
      run: sudo apt-get install detox sharutils
      shell: bash

    - name: Set git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      shell: bash

    - name: Run build_db.py
      run: python ${{ github.action_path }}/build_db.py ${{ inputs.dryrun && '-d' || '' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        DB_ID: ${{ inputs.db-name }}
