name: "MiSTer build db"
description: "Builds db file for distribution"
inputs:
  db-name:
    description: "Name of DB (value used by downloader)"
    required: true
    default: "test"
  dryrun:
    description: "Flag to skip commiting"
    required: false
runs:
  using: "composite"
  steps:
    - name: Install apt-get utilities
      run: sudo apt-get install detox sharutils
      shell: bash

    - name: Set git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      shell: bash

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run build_db.py
      run: build_db.py >> $GITHUB_OUTPUT
      shell: python
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        DB_IB: ${{ inputs.db-name }}
